### ISSUE TITLE
Include tectonic-torcx packages in the upcoming beta and stable releases (1520 / 1535)

### ISSUE THREAD

**Issue by euank** [coreos/tectonic-torcx#28]
This is a tracking issue for the purpose of our release projects.

the torcx-metadata json and docker 1.12 torcx packages should be available for both the 1520 beta and the 1535 alpha releases.

**Comment by lucab** [comment]
@euank as per https://github.com/coreos/tectonic-torcx/issues/20 we would like to close this public bug tracker. Can you please move this tracking item somewhere else?

**Comment by euank** [comment]
Moved https://github.com/coreos/bugs/issues/2144
